site_name: Test Docs
repo_url: https://github.com/kurinoshun/test-docs
theme:
  name: material
  language: ja

nav:
  - ホーム: index.md
  - 開発ガイド:
      - はじめに: docs/development/intro.md
      - コーディング規約: docs/development/coding_standards.md
      - デプロイ手順: docs/development/deployment.md
  - APIリファレンス: docs/api_reference.md
  - FAQ: docs/faq.md
  - チーム紹介: docs/team.md
  - 更新履歴: docs/changelog.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed
